version: '3'

services:
  instabot-herba:
    image: poppypop/docker-instabot:0.0-git
    command: python /app/herba.py
    environment:
      - TZ=Europe/Paris
    volumes:
      - insta-config:/app
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"
      
  instabot-herba:
    image: poppypop/docker-instabot:0.0-git
    command: python /app/cookies.py
    environment:
      - TZ=Europe/Paris
    volumes:
      - insta-cookies:/app
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"

volumes:
  insta-config:
    external: true
  insta-cookies:
    external: true
    
networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 9000
